### ISSUE TITLE
Looks not so good on smaller docks

### ISSUE THREAD

**Issue by gianmarcogg03** [JM-Enthusiast/latte-indicator-win11#1]
Looks kinda bad on my 34px icons.

![aaa](https://user-images.githubusercontent.com/28053717/141661628-0a56495a-405f-4440-a5e6-65515acfa94e.png)

If you need more info, please comment.

**Comment by JM-Enthusiast** [comment]
Hey! Sorry it took so long to get to this but I think it should be better now. Could you please test the newest version and tell me what you think?

**Comment by gianmarcogg03** [comment]
It hasn't changed at all.

**Comment by JM-Enthusiast** [comment]
I just realised I replaced the code with something that does the same calculation just differently lol. Could you show me all your Latte settings and tell me what screen resolution you have? When I tested with 34px icons on my setup it looked fine. I'll see if reproducing your setup can help me figure out something that works better.

**Comment by gianmarcogg03** [comment]
![2021-12-14_14-28](https://user-images.githubusercontent.com/28053717/146007339-d1bd478b-e4b8-4503-bb6c-86945bc89fbf.png)
![2021-12-14_14-27](https://user-images.githubusercontent.com/28053717/146007343-4c1f1229-75cb-4d81-8359-77f9e18497cb.png)

**Comment by JM-Enthusiast** [comment]
Alright thank you! I believe it should now actually look proper. Because of the way it was positionned, since you have smaller margins on the dock, the line would end up inside the icons. Now it should be correctly positionned no matter the margin thickness. Please test out the new version and let me know if everything works correctly this time!

**Comment by gianmarcogg03** [comment]
Looks good now, thank you.
